export const prices = ["", "$ = under $10", "$$ = $10-$30", "$$$ = $30-$60", "$$$$ = over $60"];

// ADD SUBCUISINES...
export const cuisines = [
  ["Afghan", "afghani"],
  ["African", "african"],
  ["American (New)", "newamerican"],
  ["American (Traditional)", "tradamerican"],
  ["Arabian", "arabian"],
  ["Argentine", "argentine"],
  ["Armenian", "armenian"],
  ["Asian Fusion", "asianfusion"],
  ["Australian", "australian"],
  ["Austrian", "austrian"],
  ["Bangladeshi", "bangladeshi"],
  ["Barbeque", "bbq"],
  ["Basque", "basque"],
  ["Belgian", "belgian"],
  ["Brasseries", "brasseries"],
  ["Brazilian", "brazilian"],
  ["Breakfast & Brunch", "breakfast_brunch"],
  ["British", "british"],
  ["Buffets", "buffets"],
  ["Bulgarian", "bulgarian"],
  ["Burgers", "burgers"],
  ["Burmese", "burmese"],
  ["Cafes", "cafes"],
  ["Cafeteria", "cafeteria"],
  ["Cajun/Creole", "cajun"],
  ["Cambodian", "cambodian"],
  ["Caribbean", "caribbean"],
  ["Catalan", "catalan"],
  ["Cheesesteaks", "cheesesteaks"],
  ["Chicken Shop", "chickenshop"],
  ["Chicken Wings", "chicken_wings"],
  ["Chinese", "chinese"],
  ["Comfort Food", "comfortfood"],
  ["Creperies", "creperies"],
  ["Cuban", "cuban"],
  ["Delis", "delis"],
  ["Diners", "diners"],
  ["Dinner Theater", "dinnertheater"],
  ["Eritrean", "eritrean"],
  ["Ethiopian", "ethiopian"],
  ["Fast Food", "hotdogs"],
  ["Filipino", "filipino"],
  ["Fish & Chips", "fishnchips"],
  ["Fondue", "fondue"],
  ["Food Court", "food_court"],
  ["Food Stands", "foodstands"],
  ["French", "french"],
  ["Game Meat", "gamemeat"],
  ["Gastropubs", "gastropubs"],
  ["German", "german"],
  ["Greek", "greek"],
  ["Guamanian", "Guamanian"],
  ["Hawaiian", "hawaiian"],
  ["Himalayan/Nepalese", "himalayan"],
  ["Honduran", "honduran"],
  ["Hong Kong Style Cafe", "hkcafe"],
  ["Hot Dogs", "hotdog"],
  ["Hot Pot", "hotpot"],
  ["Hungarian", "hungarian"],
  ["Iberian", "iberian"],
  ["Indian", "indpak"],
  ["Indonesian", "indonesian"],
  ["Irish", "irish"],
  ["Italian", "italian"],
  ["Japanese", "japanese"],
  ["Kebab", "kebab"],
  ["Korean", "korean"],
  ["Laotian", "laotian"],
  ["Latin American", "latin"],
  ["Live/Raw Food", "raw_food"],
  ["Malaysian", "malaysian"],
  ["Mediterranean", "mediterranean"],
  ["Mexican", "mexican"],
  ["Middle Eastern", "mideastern"],
  ["Mongolian", "mongolian"],
  ["Moroccan", "moroccan"],
  ["New Mexican Cuisine", "newmexican"],
  ["Nicaraguan", "nicaraguan"],
  ["Noodles", "noodles"],
  ["Pakistani", "pakistani"],
  ["Pan Asian", "panasian"],
  ["Persian/Iranian", "persian"],
  ["Peruvian", "peruvian"],
  ["Pizza", "pizza"],
  ["Polish", "polish"],
  ["Polynesian", "polynesian"],
  ["Pop-Up Restaurants", "popuprestaurants"],
  ["Portuguese", "portuguese"],
  ["Poutineries", "poutineries"],
  ["Russian", "russian"],
  ["Salad", "salad"],
  ["Sandwiches", "sandwiches"],
  ["Scandinavian", "scandinavian"],
  ["Scottish", "scottish"],
  ["Seafood", "seafood"],
  ["Singaporean", "singaporean"],
  ["Slovakian", "slovakian"],
  ["Somali", "somali"],
  ["Soul Food", "soulfood"],
  ["Soup", "soup"],
  ["Southern", "southern"],
  ["Spanish", "spanish"],
  ["Sri Lankan", "srilankan"],
  ["Steakhouses", "steak"],
  ["Supper Clubs", "supperclubs"],
  ["Sushi Bars", "sushi"],
  ["Syrian", "syrian"],
  ["Taiwanese", "taiwanese"],
  ["Tapas Bars", "tapas"],
  ["Tapas/Small Plates", "tapasmallplates"],
  ["Tex-Mex", "tex-mex"],
  ["Thai", "thai"],
  ["Turkish", "turkish"],
  ["Ukrainian", "ukrainian"],
  ["Vietnamese", "vietnamese"],
  ["Waffles", "waffles"],
  ["Wraps", "wrap"],
];

export const accomodations = [
  // categories
  ["vegan", "vegan"],
  ["vegetarian", "vegetarian"],
  ["halal", "halal"],
  ["gluten-free", "gluten_free"],
  ["kosher", "kosher"],
  // attributes
  ["gender neutral restrooms", "gender_neutral_restrooms"],
  ["open to all", "open_to_all"],
  ["wheelchair accessible", "wheelchair_accessible"],
];

export const dummyRestaurants = [
  {
    id: "XjC5H-uKRrsctioXxuCMQQ",
    alias: "torchys-tacos-austin-4",
    name: "Torchy's Tacos",
    image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/z7w3PHbZkWGXgfK2iTJuLA/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/torchys-tacos-austin-4?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 888,
    categories: [
      {
        alias: "tex-mex",
        title: "Tex-Mex",
      },
      {
        alias: "tacos",
        title: "Tacos",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 30.293709982194375,
      longitude: -97.74172805255148,
    },
    transactions: ["pickup"],
    price: "$",
    location: {
      address1: "2801 Guadalupe St",
      address2: "Ste 5-B",
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["2801 Guadalupe St", "Ste 5-B", "Austin, TX 78705"],
    },
    phone: "+15124948226",
    display_phone: "(512) 494-8226",
    distance: 1230.5624290830974,
  },
  {
    id: "1-0Jhx0QpzPk9cGcMYRUDA",
    alias: "halal-bros-austin-2",
    name: "Halal Bros",
    image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/8n-sUq_Axivu0B2Rf8jJKQ/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/halal-bros-austin-2?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 625,
    categories: [
      {
        alias: "mideastern",
        title: "Middle Eastern",
      },
      {
        alias: "halal",
        title: "Halal",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 30.29252,
      longitude: -97.74165,
    },
    transactions: ["delivery", "pickup"],
    price: "$",
    location: {
      address1: "2712 Guadalupe St",
      address2: null,
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["2712 Guadalupe St", "Austin, TX 78705"],
    },
    phone: "+15122848105",
    display_phone: "(512) 284-8105",
    distance: 1122.7645104323885,
  },
  {
    id: "-Ce8p148xb0-4dv_3zwm3A",
    alias: "cabo-bobs-burritos-austin-2",
    name: "Cabo Bob's Burritos",
    image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/3ozWv7yYgawEuBjFIxLjAw/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/cabo-bobs-burritos-austin-2?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 432,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 30.295789,
      longitude: -97.7442669,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "2828 Rio Grande St",
      address2: "",
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["2828 Rio Grande St", "Austin, TX 78705"],
    },
    phone: "+15124321112",
    display_phone: "(512) 432-1112",
    distance: 1562.8013432374264,
  },
  {
    id: "HjKbiCL6_ZvGWYx5EX4-pQ",
    alias: "freebirds-world-burrito-austin-2",
    name: "Freebirds World Burrito",
    image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/UNULFA4tmtk3pzfgEfiC5A/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/freebirds-world-burrito-austin-2?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 202,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
      {
        alias: "tex-mex",
        title: "Tex-Mex",
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 30.255912020788074,
      longitude: -97.74647,
    },
    transactions: ["delivery", "pickup"],
    price: "$",
    location: {
      address1: "515 S Congress",
      address2: "Ste 101",
      address3: "",
      city: "Austin",
      zip_code: "78704",
      country: "US",
      state: "TX",
      display_address: ["515 S Congress", "Ste 101", "Austin, TX 78704"],
    },
    phone: "+15124623512",
    display_phone: "(512) 462-3512",
    distance: 3433.447390585566,
  },
  {
    id: "_LL0cTi1MTiIl-d3Px-QNA",
    alias: "don-japanese-kitchen-austin",
    name: "Don Japanese Kitchen",
    image_url: "https://s3-media3.fl.yelpcdn.com/bphoto/yCsYKY_dWJdgs0lkACebHg/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/don-japanese-kitchen-austin?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 214,
    categories: [
      {
        alias: "foodtrucks",
        title: "Food Trucks",
      },
      {
        alias: "japanese",
        title: "Japanese",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 30.286432,
      longitude: -97.742651,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "411 W 23rd",
      address2: "",
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["411 W 23rd", "Austin, TX 78705"],
    },
    phone: "",
    display_phone: "",
    distance: 845.8575495664411,
  },
  {
    id: "q1C3m4ssFeN401uAgL1O6A",
    alias: "the-pizza-press-austin",
    name: "The Pizza Press",
    image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/KuZ6gp4-Xcr4MXHXKZkZJA/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/the-pizza-press-austin?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 186,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 30.29072,
      longitude: -97.74201,
    },
    transactions: ["delivery", "pickup"],
    price: "$",
    location: {
      address1: "404 W 26th St",
      address2: null,
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["404 W 26th St", "Austin, TX 78705"],
    },
    phone: "+15128080474",
    display_phone: "(512) 808-0474",
    distance: 1010.6073571816391,
  },
  {
    id: "0lgGW93HYeVqrTTx9d3gUA",
    alias: "chilantro-austin",
    name: "Chi'Lantro",
    image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/EgkriIi4EWfo49HPEoDJXg/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/chilantro-austin?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 717,
    categories: [
      {
        alias: "korean",
        title: "Korean",
      },
      {
        alias: "foodtrucks",
        title: "Food Trucks",
      },
      {
        alias: "bbq",
        title: "Barbeque",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 30.27007,
      longitude: -97.74187,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "823 Congress Ave",
      address2: null,
      address3: "",
      city: "Austin",
      zip_code: "78701",
      country: "US",
      state: "TX",
      display_address: ["823 Congress Ave", "Austin, TX 78701"],
    },
    phone: "+15125936290",
    display_phone: "(512) 593-6290",
    distance: 1762.8521675988761,
  },
  {
    id: "WOAUHpYxc4Ga9AuFqAqxrQ",
    alias: "taco-shack-austin-3",
    name: "Taco Shack",
    image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/kvd-VOOmqEjwq4xwjcB--w/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/taco-shack-austin-3?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 49,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
    ],
    rating: 3,
    coordinates: {
      latitude: 30.29516,
      longitude: -97.74258,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "2825 Guadalupe St",
      address2: "",
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["2825 Guadalupe St", "Austin, TX 78705"],
    },
    phone: "+15123208889",
    display_phone: "(512) 320-8889",
    distance: 1404.0287579943683,
  },
  {
    id: "g6B2TZYS7JKKpNWPwVnwqw",
    alias: "taco-joint-austin-2",
    name: "Taco Joint",
    image_url: "https://s3-media1.fl.yelpcdn.com/bphoto/pmkyEaexL3Ck4Fd22A9TuA/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/taco-joint-austin-2?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 439,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 30.291596,
      longitude: -97.734906,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "2807 & 2809 San Jacinto Blvd",
      address2: "",
      address3: "",
      city: "Austin",
      zip_code: "78705",
      country: "US",
      state: "TX",
      display_address: ["2807 & 2809 San Jacinto Blvd", "Austin, TX 78705"],
    },
    phone: "+15124738223",
    display_phone: "(512) 473-8223",
    distance: 755.7945830790921,
  },
  {
    id: "cfYWWw8579WMWe4oFsa6Gw",
    alias: "taqueria-chapala-1-austin",
    name: "Taqueria Chapala #1",
    image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/FnMKdbm6OScE2rWK1Zm_7Q/o.jpg",
    is_closed: false,
    url:
      "https://www.yelp.com/biz/taqueria-chapala-1-austin?adjust_creative=PqyTVXkk6QwcqnsD1_p9-A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=PqyTVXkk6QwcqnsD1_p9-A",
    review_count: 167,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
      {
        alias: "spanish",
        title: "Spanish",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 30.2560165363549,
      longitude: -97.7219330540115,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "2101 E Cesar Chavez St",
      address2: "",
      address3: "",
      city: "Austin",
      zip_code: "78702",
      country: "US",
      state: "TX",
      display_address: ["2101 E Cesar Chavez St", "Austin, TX 78702"],
    },
    phone: "+15123200308",
    display_phone: "(512) 320-0308",
    distance: 3411.305326876577,
  },
];

export const winner = [dummyRestaurants[9]];
